# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_beli', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order_beli', models.IntegerField(blank=True, null=True)),
                ('harga_beli_pcs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kantor_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_nota_beli', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_beli', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_masuk', models.CharField(blank=True, default='belum ada', max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('faktur_atau_tidak', models.CharField(blank=True, max_length=200, null=True)),
                ('hutang_standing', models.IntegerField(blank=True, null=True)),
                ('diorder_oleh', models.CharField(blank=True, max_length=200, null=True)),
                ('nilai_nota_beli', models.IntegerField(blank=True, null=True)),
                ('tanggal_nota_beli', models.DateField(blank=True, null=True)),
                ('jatuh_tempo_beli', models.DateField(blank=True, null=True)),
                ('status_nota_beli', models.CharField(blank=True, default='belum lunas', max_length=200, null=True)),
                ('status_barang_beli', models.CharField(blank=True, default='belum dikirim', max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('total_volume_nota', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster_pembeli', models.CharField(blank=True, default='Cikebu', max_length=200, null=True)),
            ],
        ),
    ]
