# Generated by Django 5.1.4 on 2025-02-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pembelian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailpembelian',
            old_name='no_SJ_masuk',
            new_name='id_detail_nota_masuk',
        ),
        migrations.RemoveField(
            model_name='notapembelian',
            name='no_SJ_masuk',
        ),
    ]
