# Generated by Django 5.1.4 on 2025-06-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailReturCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(blank=True, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaReturCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_retur', models.DateField(blank=True, null=True)),
                ('nilai_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
