# Generated by Django 5.1.4 on 2025-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturBarang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRetur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(blank=True, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('harga_beli', models.IntegerField(blank=True, null=True)),
                ('kondisi_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('id_detail_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaRetur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_retur', models.DateField(blank=True, null=True)),
                ('nilai_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DetailReturCart',
        ),
        migrations.DeleteModel(
            name='NotaReturCart',
        ),
    ]
