# Generated by Django 5.1.4 on 2025-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturBarang', '0002_detailretur_notaretur_delete_detailreturcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaretur',
            name='gudang_cabang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
