# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_supir', models.CharField(blank=True, max_length=200, null=True)),
                ('no_telepon_supir', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('merek_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('tahun_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kendaraan', models.CharField(blank=True, default='belum kerja', max_length=200, null=True)),
                ('max_berat', models.IntegerField(blank=True, null=True)),
                ('max_dus', models.IntegerField(blank=True, null=True)),
                ('max_rupiah', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
