# Generated by Django 5.1.4 on 2025-02-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPlanKiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('no_sj_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_tujuan_kiriman', models.CharField(blank=True, max_length=200, null=True)),
                ('GPS_lokasi_kiriman', models.CharField(blank=True, max_length=200, null=True)),
                ('no_urut_kiriman', models.IntegerField(blank=True, null=True)),
                ('id_plan_kiriman', models.CharField(blank=True, max_length=200, null=True)),
                ('id_detail_plan_kiriman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSisaNotaTerkirimSebagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('id_detail_nota', models.CharField(blank=True, max_length=200, null=True)),
                ('tujuan_kirim', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_produk', models.IntegerField(blank=True, null=True)),
                ('harga_jual_pcs', models.IntegerField(blank=True, null=True)),
                ('discount_produk', models.FloatField(blank=True, null=True)),
                ('subtotal_vol', models.FloatField(blank=True, null=True)),
                ('jumlah_order_terkirim', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanKiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('id_plan_kiriman', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_supir', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_kiriman', models.DateField(blank=True, null=True)),
                ('total_jarak_km', models.IntegerField(blank=True, null=True)),
                ('biaya_kiriman', models.IntegerField(blank=True, null=True)),
                ('start_kerja', models.DateTimeField(blank=True, null=True)),
                ('selesai_kerja', models.DateTimeField(blank=True, null=True)),
                ('ada_returan', models.BooleanField(default=False)),
                ('keterangan_retur', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateNotaKirimSebagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan_kirim', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('nilai_belum_terkirim', models.CharField(blank=True, max_length=200, null=True)),
                ('terakhir_terkirim', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kiriman', models.CharField(blank=200, max_length=200, null=200)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='tarif_rupiah_per_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
