# Generated by Django 5.1.4 on 2025-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_detailplankiriman_detailsisanotaterkirimsebagian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plankiriman',
            name='nomer_urut_kiriman',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
