# Generated by Django 5.1.4 on 2025-03-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_plankiriman_nomer_urut_kiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsisanotaterkirimsebagian',
            name='id_nota_sebagian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='updatenotakirimsebagian',
            name='id_nota_sebagian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
