# Generated by Django 5.1.4 on 2025-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='dus_per_palet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
