# Generated by Django 5.1.4 on 2025-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcustomer',
            name='audio_interview_outlet',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
