# Generated by Django 5.1.4 on 2025-02-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_registeredcustomer_audio_interview_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcustomer',
            name='frequency_kunjungan',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('belum ada', 'belum ada')], default='belum ada', max_length=200, null=True),
        ),
    ]
