# Generated by Django 5.1.4 on 2025-03-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_registeredcustomer_frequency_kunjungan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt_name', models.CharField(blank=True, max_length=200, null=True)),
                ('default_prompt', models.TextField(blank=True, null=True)),
                ('adjusted_prompt', models.TextField(blank=True, null=True)),
                ('prompt_description', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_prompt', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
