# Generated by Django 5.1.4 on 2025-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarPromosiBerjalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_promo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipe_promo', models.CharField(blank=True, choices=[('single produk', 'single produk'), ('by merek', 'by merek'), ('by submerek', 'by submerek'), ('by tiersegmen', 'by tiersegmen'), ('by usersegmen', 'by usersegmen'), ('by kategori', 'by kategori'), ('by klasifikasi', 'by klasifikasi'), ('by spek', 'by spek'), ('by produsen', 'by produsen'), ('by jenis', 'by jenis'), ('all produk', 'all produk')], max_length=200, null=True)),
                ('pembuat_promo', models.CharField(blank=True, choices=[('single produk', 'single produk'), ('by merek', 'by merek'), ('by submerek', 'by submerek'), ('by tiersegmen', 'by tiersegmen'), ('by usersegmen', 'by usersegmen'), ('by kategori', 'by kategori'), ('by klasifikasi', 'by klasifikasi'), ('by spek', 'by spek'), ('by produsen', 'by produsen'), ('by jenis', 'by jenis'), ('all produk', 'all produk')], max_length=200, null=True)),
                ('deskripsi_promo', models.CharField(blank=True, max_length=200, null=True)),
                ('yang_dipromokan', models.CharField(blank=True, max_length=200, null=True)),
                ('wajib_upload_tidak', models.BooleanField(default=False)),
                ('alias_promo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='kontrakoutletpromotion',
            name='deskripsi_promo',
        ),
        migrations.RemoveField(
            model_name='kontrakoutletpromotion',
            name='tipe_promo',
        ),
        migrations.RemoveField(
            model_name='kontrakoutletpromotion',
            name='yang_dipromokan',
        ),
        migrations.AddField(
            model_name='kontrakoutletpromotion',
            name='data_keikutsertaan',
            field=models.ImageField(blank=True, null=True, upload_to='kontrak_outlet/data_keikutsertaan'),
        ),
        migrations.AddField(
            model_name='loyaltypointcustomer',
            name='loyalty_heart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
