# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('foto_lokasi', models.ImageField(blank=True, null=True, upload_to='photo_lokasi_gudang/')),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(default=0)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('opname_id', models.CharField(blank=True, max_length=200, null=True)),
                ('hasil_opname', models.BooleanField(default=True)),
                ('nominal_selisih', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_transit', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('harga_modal_pcs', models.IntegerField(blank=True, null=True)),
                ('jumlah_barang', models.IntegerField(default=0)),
                ('tujuan_kirim', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_transit', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
