# Generated by Django 5.1.4 on 2025-02-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_audit_stok', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('stok_fisik_teraudit', models.IntegerField(default=0)),
                ('stok_utama_buku', models.IntegerField(default=0)),
                ('selisih', models.IntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(default=0)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KartuStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('id_ks_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('id_sj_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_transaksi', models.IntegerField(default=0)),
                ('estimasi_harga_beli', models.IntegerField(default=0)),
                ('stok_awal', models.IntegerField(default=0)),
                ('stok_akhir', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(default=0)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_lokasi', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_beli_weighted', models.IntegerField(default=0)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stok',
        ),
    ]
