# Generated by Django 5.1.4 on 2025-03-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0002_auditstok_kartustok_stokutama_delete_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelisihBongkarMuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sj_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('id_ks_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_selisih', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('status_selisih', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
