# Generated by Django 5.1.4 on 2025-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0003_selisihbongkarmuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokutama',
            name='detail_lokasi',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], default='Kosong', max_length=200, null=True),
        ),
    ]
