# Generated by Django 5.1.4 on 2025-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0004_alter_stokutama_detail_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartustok',
            name='tahun_produksi_produk',
            field=models.IntegerField(default=0),
        ),
    ]
