# Generated by Django 5.1.4 on 2025-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0005_kartustok_tahun_produksi_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstok',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
