# Generated by Django 5.1.4 on 2025-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stok', '0006_auditstok_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasistok',
            name='jenis_lokasi',
            field=models.CharField(blank=True, choices=[('Gudang Pcs', 'Gudang Pcs'), ('Gudang Dus', 'Gudang Dus'), ('Gudang Palet', 'Gudang Palet')], default='Kosong', max_length=200, null=True),
        ),
    ]
