# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, default='belum ada', max_length=200, null=True)),
                ('kode_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order', models.IntegerField(blank=True, null=True)),
                ('harga_jual_pcs', models.IntegerField(blank=True, null=True)),
                ('discount_produk', models.FloatField(blank=True, null=True)),
                ('subtotal_vol', models.FloatField(blank=True, null=True)),
                ('tanggal_nota', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, default='belum ada', max_length=200, null=True)),
                ('jenis_penjualan', models.CharField(blank=True, choices=[('2W', '2W'), ('4W', '4W'), ('6W', '6W'), ('Industrial', 'Industrial')], default='offline', max_length=200, null=True)),
                ('jenis_faktur', models.CharField(blank=True, choices=[('2W', '2W'), ('4W', '4W'), ('6W', '6W'), ('Industrial', 'Industrial')], default='tanpa faktur', max_length=200, null=True)),
                ('nilai_nota_jual', models.IntegerField(blank=True, default=0, null=True)),
                ('piutang_standing', models.IntegerField(blank=True, default=0, null=True)),
                ('kantor_cabang', models.CharField(blank=True, choices=[('2W', '2W'), ('4W', '4W'), ('6W', '6W'), ('Industrial', 'Industrial')], max_length=200, null=True)),
                ('nama_salesman', models.CharField(blank=True, choices=[('Supervisor Cikebu', 'Supervisor Cikebu'), ('Supervisor Babawopa', 'Supervisor Babawopa'), ('Supervisor Temapur', 'Supervisor Temapur'), ('Supervisor DIY', 'Supervisor DIY'), ('Sales Cilacap Barat', 'Sales Cilacap Barat'), ('Sales Cilacap Timur', 'Sales Cilacap Timur'), ('Sales Kebumen ', 'Sales Kebumen'), ('Sales Wonosobo', 'Sales Wonosobo'), ('Sales Banjarnegara Purbalingga', 'Sales Banjarnegara Purbalingga'), ('Sales Banyumas', 'Sales Banyumas'), ('Sales Magelang', 'Sales Magelang'), ('Sales Purworejo', 'Sales Purworejo'), ('Sales Jogja Barat Daya', 'Sales Jogja Barat Daya'), ('Sales Jogja Barat Laut', 'Sales Jogja Barat Laut'), ('Sales Jogja Tenggara', 'Sales Jogja Tenggara'), ('Sales Jogja Timur Laut', 'Sales Jogja Timur Laut'), ('Kantor DIY', 'Kantor DIY'), ('Kantor Cikebu', 'Kantor Cikebu'), ('Kantor Babawopa', 'Kantor Babawopa'), ('Kantor Temapur', 'Kantor Temapur'), ('Sales Industry Barat', 'Sales Industry Barat'), ('Sales Industry Timur', 'Sales Industry Timur'), ('Sales Industry Tengah', 'Sales Industry Tengah'), ('Sales Klaten', 'Sales Klaten')], max_length=200, null=True)),
                ('status_nota', models.CharField(blank=True, default='belum lunas', max_length=200, null=True)),
                ('status_barang', models.CharField(blank=True, default='belum dikirim', max_length=200, null=True)),
                ('tanggal_nota', models.DateField(blank=True, null=True)),
                ('jatuh_tempo_nota', models.DateField(blank=True, null=True)),
                ('divisi_kantor', models.CharField(blank=True, choices=[('Pelumas', 'Pelumas'), ('LPG NPSO', 'LPG NPSO'), ('LPG PSO', 'LPG PSO'), ('Minyak Inmar', 'Minyak Inmar'), ('Customer Goods', 'Customer Goods')], max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, choices=[('PT. Gelora Putra Perkasa', 'PT. Gelora Putra Perkasa'), ('PT. Gelora Portalindo', 'PT. Gelora Portalindo'), ('PT. Buana Rahayu', 'PT Buana Rahayu'), ('PT. Sochi Jaya Sentosa', 'PT. Sochi Jaya Sentosa'), ('PT. Serayu Mitra Jaya', 'PT. Serayu Mitra Jaya')], max_length=200, null=True)),
                ('ikut_program_apa', models.CharField(blank=True, default='tidak ikut', max_length=200, null=True)),
                ('catatan_tambahan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
