# Generated by Django 5.1.4 on 2025-01-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjualan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order', models.IntegerField(blank=True, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_produk', models.FloatField(blank=True, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_jual_pcs', models.IntegerField(blank=True, null=True)),
                ('kantor_cabang', models.CharField(blank=True, default='Cilacap', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingNotaPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_jual', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_penjualan', models.CharField(blank=True, choices=[('2W', '2W'), ('4W', '4W'), ('6W', '6W'), ('Industrial', 'Industrial')], default='offline', max_length=200, null=True)),
                ('jenis_faktur', models.BooleanField()),
                ('nilai_nota_jual', models.IntegerField(blank=True, default=0, null=True)),
                ('nama_salesman', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_nota', models.DateField(blank=True, null=True)),
                ('jatuh_tempo_nota', models.DateField(blank=True, null=True)),
                ('kantor_cabang', models.CharField(blank=True, choices=[('2W', '2W'), ('4W', '4W'), ('6W', '6W'), ('Industrial', 'Industrial')], max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, choices=[('Pelumas', 'Pelumas'), ('LPG NPSO', 'LPG NPSO'), ('LPG PSO', 'LPG PSO'), ('Minyak Inmar', 'Minyak Inmar'), ('Customer Goods', 'Customer Goods')], default='Pelumas', max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, choices=[('PT. Gelora Putra Perkasa', 'PT. Gelora Putra Perkasa'), ('PT. Gelora Portalindo', 'PT. Gelora Portalindo'), ('PT. Buana Rahayu', 'PT Buana Rahayu'), ('PT. Sochi Jaya Sentosa', 'PT. Sochi Jaya Sentosa'), ('PT. Serayu Mitra Jaya', 'PT. Serayu Mitra Jaya')], default='PT. Gelora Putra Perkasa', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detailpenjualan',
            name='jumlah_order_terkirim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
