# Generated by Django 5.1.4 on 2025-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjualan', '0002_pendingdetailpenjualan_pendingnotapenjualan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpenjualan',
            name='no_SJ_keluar',
        ),
        migrations.RemoveField(
            model_name='notapenjualan',
            name='no_SJ_keluar',
        ),
        migrations.AddField(
            model_name='detailpenjualan',
            name='id_detail_nota_jual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notapenjualan',
            name='jenis_faktur',
            field=models.CharField(blank=True, choices=[('Print Faktur', 'Print Faktur'), ('Faktur tidak Print', 'Faktur tidak Print'), ('Gunggung', 'Gunggung'), ('Offline Req Gunggung', 'Offline Req Gunggung')], default='tanpa faktur', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notapenjualan',
            name='jenis_penjualan',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('Tokopedia', 'Tokopedia'), ('Blibli', 'Blibli'), ('Power', 'Power')], default='offline', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notapenjualan',
            name='kantor_cabang',
            field=models.CharField(blank=True, choices=[('Cilacap', 'Cilacap'), ('Jogja', 'Jogja'), ('Purwokerto', 'Purwokerto'), ('Magelang', 'Magelang'), ('Wonosobo', 'Wonosobo'), ('Klaten', 'Klaten'), ('Kebumen', 'Kebumen'), ('Purworejo', 'Purworejo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pendingnotapenjualan',
            name='jenis_penjualan',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('Tokopedia', 'Tokopedia'), ('Blibli', 'Blibli'), ('Power', 'Power')], default='offline', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pendingnotapenjualan',
            name='kantor_cabang',
            field=models.CharField(blank=True, choices=[('Cilacap', 'Cilacap'), ('Jogja', 'Jogja'), ('Purwokerto', 'Purwokerto'), ('Magelang', 'Magelang'), ('Wonosobo', 'Wonosobo'), ('Klaten', 'Klaten'), ('Kebumen', 'Kebumen'), ('Purworejo', 'Purworejo')], max_length=200, null=True),
        ),
    ]
