# Generated by Django 5.1.4 on 2025-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjualan', '0003_remove_detailpenjualan_no_sj_keluar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapenjualan',
            name='jenis_faktur',
            field=models.CharField(blank=True, choices=[('Print Faktur', 'Print Faktur'), ('Faktur tidak Print', 'Faktur tidak Print'), ('Tanpa Faktur', 'Tanpa Faktur'), ('Gunggung', 'Gunggung'), ('Offline Req Gunggung', 'Offline Req Gunggung')], default='tanpa faktur', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notapenjualan',
            name='jenis_penjualan',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('Tokopedia', 'Tokopedia'), ('Blibli', 'Blibli'), ('Power', 'Power'), ('Pembelian di Kantor', 'Pembelian di Kantor')], default='offline', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pendingnotapenjualan',
            name='jenis_penjualan',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('Tokopedia', 'Tokopedia'), ('Blibli', 'Blibli'), ('Power', 'Power'), ('Pembelian di Kantor', 'Pembelian di Kantor')], default='offline', max_length=200, null=True),
        ),
    ]
