# Generated by Django 5.1.4 on 2025-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penjualan', '0004_alter_notapenjualan_jenis_faktur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapenjualan',
            name='nama_salesman',
            field=models.CharField(blank=True, choices=[('Supervisor Cikebu', 'Supervisor Cikebu'), ('Supervisor Babawopa', 'Supervisor Babawopa'), ('Supervisor Temapur', 'Supervisor Temapur'), ('Supervisor DIY', 'Supervisor DIY'), ('Sales Cilacap Barat', 'Sales Cilacap Barat'), ('Sales Cilacap Timur', 'Sales Cilacap Timur'), ('Sales Kebumen ', 'Sales Kebumen'), ('Sales Wonosobo', 'Sales Wonosobo'), ('Sales Banjarnegara Purbalingga', 'Sales Banjarnegara Purbalingga'), ('Sales Banyumas', 'Sales Banyumas'), ('Sales Magelang', 'Sales Magelang'), ('Sales Purworejo', 'Sales Purworejo'), ('Sales Jogja Barat Daya', 'Sales Jogja Barat Daya'), ('Sales Jogja Barat Laut', 'Sales Jogja Barat Laut'), ('Sales Jogja Tenggara', 'Sales Jogja Tenggara'), ('Sales Jogja Timur Laut', 'Sales Jogja Timur Laut'), ('Sales Jogja Kota', 'Sales Jogja Kota'), ('Kantor DIY', 'Kantor DIY'), ('Kantor Cikebu', 'Kantor Cikebu'), ('Kantor Babawopa', 'Kantor Babawopa'), ('Kantor Temapur', 'Kantor Temapur'), ('Sales Industry Barat', 'Sales Industry Barat'), ('Sales Industry Timur', 'Sales Industry Timur'), ('Sales Industry Tengah', 'Sales Industry Tengah')], max_length=200, null=True),
        ),
    ]
