# Generated by Django 5.1.4 on 2025-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JualanRekomender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('dms_rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('produk_dijual', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pembeli', models.CharField(blank=True, max_length=200, null=True)),
                ('no_telp_pembeli', models.CharField(blank=True, max_length=200, null=True)),
                ('foto_upload', models.ImageField(blank=True, null=True, upload_to='uploads/rekomender/')),
                ('reward_spin_wheel', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('status_reward_rekomender', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rekomender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('dms_rekomender', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_per_liter', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardSpinWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reward', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_dms', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_reward', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
