# Generated by Django 5.1.4 on 2025-08-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekomender',
            name='foto_qr',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/qrcode/'),
        ),
    ]
