# Generated by Django 5.1.4 on 2025-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0002_rekomender_foto_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('probabilitas', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_barang', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jualanrekomender',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jualanrekomender',
            name='status_reward_rekomender',
            field=models.CharField(choices=[('Belum diberikan', 'Belum diberikan'), ('Sudah diberikan', 'Sudah diberikan')], default='Belum diberikan', max_length=50),
        ),
    ]
