# Generated by Django 5.1.4 on 2025-09-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0003_rewardlist_jualanrekomender_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekomender',
            name='no_telp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
