# Generated by Django 5.1.4 on 2025-09-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0004_rekomender_no_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardlist',
            name='kode_dms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
