# Generated by Django 5.1.4 on 2025-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0005_rewardlist_kode_dms'),
    ]

    operations = [
        migrations.AddField(
            model_name='jualanrekomender',
            name='id_rekomender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
