# Generated by Django 5.1.4 on 2025-09-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0006_jualanrekomender_id_rekomender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jualanrekomender',
            name='kemasan_produk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
