# Generated by Django 5.1.4 on 2025-09-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0007_jualanrekomender_kemasan_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jualanrekomender',
            name='jumlah_produk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
