# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLokasiMasukProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_keluar_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_produk', models.IntegerField(blank=True, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_beli_pcs', models.IntegerField(blank=True, null=True)),
                ('gudang_awal', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_produk', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSJMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_SJ_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order', models.IntegerField(blank=True, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_beli_pcs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SJMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_SJ_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pembawa', models.CharField(blank=True, max_length=200, null=True)),
                ('asal_kiriman', models.CharField(blank=True, max_length=200, null=True)),
                ('waktu_masuk', models.DateTimeField(blank=True, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_penerima', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_sj_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('modal_SJ_masuk', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
