# Generated by Django 5.1.4 on 2025-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuratJalanMasuk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sjmasuk',
            old_name='waktu_masuk',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='detailsjmasuk',
            name='asal_kiriman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjmasuk',
            name='id_detailSJM',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjmasuk',
            name='id_detail_nota_masuk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjmasuk',
            name='jenis_sj_masuk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjmasuk',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
