# Generated by Django 5.1.4 on 2025-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuratJalanMasuk', '0002_rename_waktu_masuk_sjmasuk_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjmasuk',
            name='status_barang',
            field=models.CharField(blank=True, default='belum dibongkar', max_length=200, null=True),
        ),
    ]
