# Generated by Django 5.1.4 on 2025-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuratJalanMasuk', '0003_sjmasuk_status_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='SJMasukRetur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_SJM_reutr', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_retur', models.CharField(blank=True, max_length=200, null=True)),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pembawa', models.CharField(blank=True, max_length=200, null=True)),
                ('waktu_masuk', models.DateTimeField(blank=True, null=True)),
                ('gudang_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_penerima', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_sj_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('foto_notasj', models.ImageField(blank=True, null=True, upload_to='sjmasuk_img/')),
                ('foto_bongkar', models.ImageField(blank=True, null=True, upload_to='sjmasuk_img/')),
                ('status_confirmasi', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
