# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('debit_kredit', models.CharField(blank=True, choices=[('debit', 'debit'), ('kredit', 'kredit')], max_length=200, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('nominal', models.IntegerField(blank=True, null=True)),
                ('kode_transaksi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kas', models.DateTimeField(blank=True, null=True)),
                ('keluar_masuk', models.CharField(blank=True, max_length=200, null=True)),
                ('bentuk_kas', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_kas', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('nilai_transaksi', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('kantor_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabelNeracaAwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_data', models.CharField(blank=True, max_length=200, null=True)),
                ('saldo_awal', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
