# Generated by Django 5.1.4 on 2025-07-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerKas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JurnalEntry',
        ),
        migrations.DeleteModel(
            name='TabelNeracaAwal',
        ),
    ]
