# Generated by Django 5.1.4 on 2025-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerKas', '0003_journalentry_journalentryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='kas',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kas',
            name='tanggal_kas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
