# Generated by Django 5.1.4 on 2025-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMutasiKeluarCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order', models.IntegerField(blank=True, null=True)),
                ('tanggal_mutasi', models.DateField(blank=True, null=True)),
                ('harga_modal_pcs', models.IntegerField(blank=True, null=True)),
                ('no_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('id_detail_mutasi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaMutasiKeluarCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, default='Pelumas', max_length=200, null=True)),
                ('gudang_awal', models.CharField(blank=True, max_length=200, null=True)),
                ('tujuan_kirim', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pengirim', models.CharField(blank=True, max_length=200, null=True)),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_mutasi', models.DateField(blank=True, null=True)),
                ('no_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kiriman', models.CharField(blank=True, default='belum dikirim', max_length=200, null=True)),
                ('nilai_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan_mutasi', models.CharField(blank=True, default='sesuai', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerimaMutasiCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerima', models.CharField(blank=True, max_length=200, null=True)),
                ('no_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_mutasi', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_diterima', models.DateField(blank=True, null=True)),
                ('status_penerimaan', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan_penerimaan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
