# Generated by Django 5.1.4 on 2025-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkunPembukuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('tipe_akun', models.CharField(blank=True, choices=[('Aset', 'Aset'), ('Hutang', 'Hutang'), ('Modal', 'Pendapatan'), ('Pengeluaran', 'Pengeluaran')], max_length=200, null=True)),
            ],
        ),
    ]
