# Generated by Django 5.1.4 on 2025-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_action', models.CharField(blank=True, max_length=200, null=True)),
                ('detaildeskripsi', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateField(auto_now=True, null=True)),
                ('kode_entry', models.CharField(blank=True, max_length=200, null=True)),
                ('validitas', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_entry', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('tipe_journal', models.CharField(blank=True, max_length=200, null=True)),
                ('value_transaksi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='akunpembukuan',
            name='deskripsi_akun',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
