# Generated by Django 5.1.4 on 2025-07-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kas', '0002_journalentry_journalentryline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
    ]
