# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori_akun', models.CharField(blank=True, max_length=200, null=True)),
                ('jabatan_user', models.CharField(blank=True, max_length=200, null=True)),
                ('authorisasi', models.CharField(blank=True, max_length=200, null=True)),
                ('profil_kode', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('no_KTP', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_KTP', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster', models.CharField(blank=True, max_length=200, null=True)),
                ('perusahaan_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('divisi_kantor', models.CharField(blank=True, max_length=200, null=True)),
                ('kantor_cabang', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
