# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('target_minimum', models.IntegerField(blank=True, null=True)),
                ('target_incentive', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TugasSalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('tugas_diberikan', models.CharField(blank=True, max_length=200, null=True)),
                ('hasil_tugas', models.BooleanField(default=False)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
