# Generated by Django 5.1.4 on 2025-02-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanSalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('tugas_ke_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('catatan_ke_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('info_dari_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sales', models.CharField(blank=True, max_length=200, null=True)),
                ('kas_disales', models.IntegerField(blank=True, null=True)),
                ('target_minimum', models.IntegerField(blank=True, null=True)),
                ('target_incentive', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TargetSalesman',
        ),
        migrations.DeleteModel(
            name='TugasSalesman',
        ),
    ]
