# Generated by Django 5.1.4 on 2025-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLokasiKeluarProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_keluar_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_produk', models.IntegerField(blank=True, null=True)),
                ('harga_modal_produk', models.IntegerField(blank=True, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('gudang_awal', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_produk', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSJKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_order', models.IntegerField(blank=True, null=True)),
                ('kemasan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_beli_produk', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SJKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('no_SJ_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('no_kendaraan', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pengirim', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_kirim', models.DateTimeField(blank=True, null=True)),
                ('gudang_awal', models.CharField(blank=True, max_length=200, null=True)),
                ('tujuan_kirim', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_sj_keluar', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kiriman', models.CharField(blank=True, default='belum sampai', max_length=200, null=True)),
                ('modal_SJ_keluar', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
