# Generated by Django 5.1.4 on 2025-02-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuratJalanKeluar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sjkeluar',
            old_name='tanggal_kirim',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='detailsjkeluar',
            name='id_detailSJK',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjkeluar',
            name='jenis_sj_keluar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailsjkeluar',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsjkeluar',
            name='tujuan_kirim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
