# Generated by Django 5.1.4 on 2025-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuratJalanKeluar', '0002_rename_tanggal_kirim_sjkeluar_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsjkeluar',
            name='id_detail_nota_keluar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
